# Experiment 1: Data Wrangling I

In [ ]:
pip install pandas

In [ ]:
import pandas as pd

In [7]:
df = pd.read_csv("/content/StudentsPerformance.csv")

In [ ]:
print(df)

In [9]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [10]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  1
dtype: int64

In [11]:
# axis=1

#Specifies columns.

#axis=0 → rows

#axis=1 → columns

In [12]:
df.dropna(axis=1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score
0,female,group B,bachelor's degree,standard,none,72,72
1,female,group C,some college,standard,completed,69,90
2,female,group B,master's degree,standard,none,90,95
3,male,group A,associate's degree,free/reduced,none,47,57
4,male,group C,some college,standard,none,76,78
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99
996,male,group C,high school,free/reduced,none,62,55
997,female,group C,high school,free/reduced,completed,59,71
998,female,group D,some college,standard,completed,68,78
999,female,group D,some college,free/reduced,none,77,86

In [ ]:
print(df.describe())

In [14]:
df.dtypes

gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                       int64
reading score                    int64
writing score                  float64
dtype: object

In [ ]:
y = df.iloc[:, 0:2]
print(y)

In [ ]:
from sklearn.preprocessing import LabelEncoder
y = ['male', 'female']
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

In [ ]:
print(df['race/ethnicity'].value_counts())

In [ ]:
df_Lunch = pd.get_dummies(df['lunch'])
df_new = pd.concat([df, df_Lunch], axis=1)#pd.concat() joins DataFrames together.axis=1 means join column-wise.
#This adds the new one-hot encoded columns to the original DataFrame.
print(df_new)

In [ ]:
from sklearn.preprocessing import LabelEncoder

y = ['Yes', 'No', 'Yes', 'No']   # define y first

le = LabelEncoder()
y = le.fit_transform(y)

print(y)

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("StudentsPerformance.csv")

y = df['gender']   # column name containing labels

le = LabelEncoder()
y = le.fit_transform(y) #fit(): finds unique classes in y transform(): assigns numbers to each class.


print(y)

In [26]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,NaN
1,female,group C,some college,standard,completed,69,90,88.0
2,female,group B,master's degree,standard,none,90,95,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44.0
4,male,group C,some college,standard,none,76,78,75.0