In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('/content/Social_Network_Ads.csv')

In [3]:
dataset.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
dataset.info()

In [5]:
dataset.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
dataset.shape

In [7]:
x = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [ ]:
print(x)

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [11]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [12]:
y_pred = classifier.predict(x_test)

In [ ]:
print(y_pred)

In [ ]:
print(y_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

In [ ]:
Accuracy=(74+30)/120
Accuracy

In [ ]:
Error_rate=(5+11)/120
Error_rate

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

In [ ]:
from sklearn.metrics import precision_score, recall_score
precision_score(y_test, y_pred)

In [ ]:
recall_score(y_test, y_pred)

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

In [22]:
from google.colab import files

uploaded = files.upload()

if uploaded:
    print("Success")
else:
    print("No file uploaded")

No file uploaded